In [10]:
import numpy as np

In [13]:
# UNIDIMENSIONAL
array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [14]:
# BIDIMENSIONAL
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [17]:
# Array de ceros
zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# Array de unos
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Array con valores aleatorios
random_array = np.random.rand(4,4)
print(random_array)

[[0.42640612 0.88751652 0.59202774 0.6562922 ]
 [0.2360024  0.76058842 0.1861085  0.85066932]
 [0.28259501 0.70701688 0.9138009  0.34640257]
 [0.89774724 0.21321427 0.02880788 0.45184011]]


In [21]:
# Array con una secuencia de numeros
sequence_array = np.arange(0,10,2)
print(sequence_array)

[0 2 4 6 8]


In [23]:
# Array con valores igualmente espaciados
linspace_array = np.linspace(0,10,5)
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


In [25]:
# Accediendo a elementos de un vector 1D
print(array_1d[0]) # Primer elementos

1


In [27]:
# Accediendo a elementos de un vector
print(array_1d[-1]) # Ultimo elemento

5


In [28]:
# Accediendo a elementos de una matriz 2D
print(array_2d[0, 1]) # 

2


In [34]:
# Slicing de vector
print(array_1d[2:4])

[3 4]


In [31]:
# Slicing de matriz 2D
print(array_2d[:, 1])

[2 5]


In [32]:
# Suma de Arrays
suma = array_1d + 10
print(suma)

[11 12 13 14 15]


In [33]:
# Resta de Arrays
resta = array_1d - 2
print(resta)

[-1  0  1  2  3]


In [35]:
# Multiplicacion de arrays
multiplicacion = array_1d * 2
print(multiplicacion)

[ 2  4  6  8 10]


In [36]:
# Division de arrays
division = array_1d / 2
print(division)

[0.5 1.  1.5 2.  2.5]


In [37]:
# OPERACIONES FUNDAMENTALES ENTRE ARRAYS
array_1d_2 = np.array([5,4,3,2,1])
elementwise_sum = array_1d + array_1d_2
print(elementwise_sum)

[6 6 6 6 6]


In [40]:
# Funciones universales
sqrt_array = np.sqrt(array_1d[0])
log_array = np.log(array_1d[1])
print(f"Resultado de sqrt {sqrt_array}")
print(f"Resultado de log {log_array}")

Resultado de sqrt 1.0
Resultado de log 0.6931471805599453


In [42]:
# Broadcasting
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d)
array_1d = np.array([1,2,3])
broadcast_result = array_2d + array_1d
print(f"Suma de arrays con diferente dimensionalidad {broadcast_result}")

[[1 2 3]
 [4 5 6]]
Suma de arrays con diferente dimensionalidad [[2 4 6]
 [5 7 9]]


In [44]:
# Funciones y Operaciones avanzadas con arrays
# FUNCIONES DE AGREGACION
# SUMA DE TODOS LOS ELEMENTOS DEL ARRAY
suma_total = np.sum(array_1d)
print(suma_total)

6


In [45]:
# Media, mediana y desviacion estandar
media = np.mean(array_1d)
mediana = np.median(array_1d)
std_dev = np.std(array_1d)
print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Desviacion estandar: {std_dev}")

Media: 2.0
Mediana: 2.0
Desviacion estandar: 0.816496580927726


In [51]:
# Producto punto entre dos arrays de 1D
array_1d = [1,2,3,4,5]
dot_product = np.dot(array_1d, array_1d_2)
print(dot_product)

35


In [52]:
array_1 = np.arange(1,11)
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10]
